### ISSUE TITLE
Automated build on docked hub failed

### ISSUE THREAD

**Issue by krishofmans** [nkatsaros/docker-atlassian-confluence#1]
Hello,

For the confluence build of 5.10 the automated build has failed. See https://hub.docker.com/r/nkatsaros/atlassian-confluence/builds/b6cqa7vfhhrznu2munepobn/ 

While building locally everything builds and works fine, but the preferred solution is that we could just pull from docker hub. 

Hopefully this can be fixed by just retriggering the build.

Thanks,
Kris

**Comment by sanderverschuren** [comment]
It would also be nice to have a build for the 5.10.1 version of confluence. 
Much appreciated!

**Comment by nkatsaros** [comment]
Just ran all my update scripts again and triggered new builds. hub.docker.com gets dumb sometimes and fails builds that should work and I forgot to trigger them manually. I'll keep an eye on it over the next day and make sure they are all working fine.

**Comment by krishofmans** [comment]
Great, thank you very much, I will give it a try asap 👍

**Comment by krishofmans** [comment]
Hi, 

Sorry for the delay, just upgraded the whole stack using docker-compose, everything is working great now, running all the latest versions.

Thanks,
Kris
